web/router.ex
defmodule Charts.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Charts do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/test", PageController, :test
    resources "/users", UsersController, only: [:new, :create]
    get "/users/login", UsersController, :login
    get "/users/:id/logout", UsersController, :logout
    post "/user/process_login", UsersController, :process_login
  end

  #Other scopes may use custom stacks.
  scope "/api", Charts, as: :api do
    pipe_through :api

    get "/charts/:id/:token", API.ChartsController, :show
    post "/charts/:id/data/:token", API.ChartsController, :data
  end


  scope "/:user_id", Charts do
    pipe_through :browser # Use the default browser stack
    get "/dashboard", UsersController, :dashboard
    get "/settings", UsersController, :settings
    patch "/token", UsersController, :token
    resources "/charts", ChartsController
  end




  socket "/ws", Charts do
    channel "data:*", DataChannel
  end
end

web/views/layout_view.ex
defmodule Charts.LayoutView do
  use Charts.View

  def menu_item([_user_id, "charts"]), do: :charts
  def menu_item([_user_id, "charts", _id]), do: :charts
  def menu_item([_user_id, "charts", _id, _action]), do: :charts
  def menu_item([_user_id, "dashboard"]), do: :dashboard
  def menu_item([_user_id, "settings"]), do: :settings
  def menu_item(["users", "new"]), do: :sign_up
  def menu_item(["users", "login"]), do: :log_in
  def menu_item(_), do: :something


end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

  <script type="text/javascript" src="/js/phoenix.js"></script>
  <script type="text/javascript" src="/js/app.js"></script>

  <script type="text/javascript"
  src="https://www.google.com/jsapi?autoload={
    'modules':[{
      'name':'visualization',
      'version':'1',
      'packages':['corechart']
    }]
  }"></script>

  <title>Charts</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/css/justified-nav.css">

</head>


<body>

  <div class="container">

    <div class="masthead">
      <%= if current_user(@conn) do %>
      <h3 class="text-muted"><%= current_user(@conn).username %></h3>
      <% else %>
      <h3 class="text-muted">Live Charts</h3>
      <% end %>
      <nav>
        <ul class="nav nav-justified">
          <% IO.puts(inspect @conn.path_info) %>
          <%= if current_user(@conn) do %>
          <li class="<%= if menu_item(@conn.path_info) == :dashboard, do: "active" %>">
            <a href="<%= users_path(@conn, :dashboard, current_user(@conn).id) %>">Dashboard</a>
          </li>
          <li class="<%= if menu_item(@conn.path_info) == :charts, do: "active" %>">
            <a href="<%= charts_path(@conn, :index, current_user(@conn).id) %>">Charts</a>
          </li>
          <li class="<%= if menu_item(@conn.path_info) == :settings, do: "active" %>">
            <a href="<%= users_path(@conn, :settings, current_user(@conn).id) %>">Settings</a>
          </li>
          <% else %>
          <li><a href="#">About</a></li>
          <% end %>
            <% current_user = current_user(@conn) %>
            <%= if current_user do %>
            <li><a href="<%= users_path @conn, :logout, current_user.id %>">Logout</a></li>
            <% else %>
            <li class="<%= if menu_item(@conn.path_info) == :log_in, do: "active" %>">
              <a href="<%= users_path @conn, :login %>">Log in</a>
            </li>
            <li class="<%= if menu_item(@conn.path_info) == :sign_up, do: "active" %>">
              <a href="<%= users_path @conn, :new %>">Sign up</a>
            </li>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>

    <%= if get_flash(@conn, :notice) do %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= get_flash(@conn, :notice) %>
    </div>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= get_flash(@conn, :error) %>
    </div>
    <% end %>



    <%= @inner %>
    <!-- Jumbotron -->


    <!-- Site footer -->
    <footer class="footer">
      <p>© antonmi 2014</p>
    </footer>

  </div> <!-- /container -->
  <%= render(__MODULE__, "inline_script.html", %{}) %>

</body>
</html>

web/templates/layout/inline_script.html.eex
<script type="text/javascript">
$('button[name="confirm-button"]').on('click', function(e){
  var text = $(this).attr("data-text")
  var $form=$(this).closest('form');
  e.preventDefault();
  if (confirm(text)) {
    $form.trigger('submit'); // submit the form
  }
});
</script>